version: 2.1

jobs:
  build-and-test:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run: pip install .
      - run: scrapy crawl freeproxylists

workflows:
  main:
    jobs:
      - build-and-test
