version: 2.1

jobs:
  build-and-test:
    docker:
      - image: python:latest
      - image: selenium/standalone-chrome  # http://127.0.0.1:4444/wd/hub
    steps:
      - checkout
      - run: pip install .
      - run: scrapy crawl freeproxylists

workflows:
  main:
    jobs:
      - build-and-test
