name: CrawlingTest
on: [push]

jobs:
  build:
    name: CrawlingTest
    runs-on: ubuntu-latest
    steps:
      - run: apt install python python-pip
      - run: pip install .
      - run: scrapy crawl freeproxylists
