name: CrawlingTest
on: [push]

jobs:
  build:
    name: CrawlingTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - run: pwd
      - run: ls
      - run: sudo apt-get install -y python python-pip
      - run: pip install .
      - run: scrapy crawl freeproxylists
